Required CSVs: salaries.csv, position.csv

Required jsons: professor_ratings.json

Cal Poly Professor ratings scraped from https://polyratings.dev/search/name. Data collected + example:

| LastName | FirstName | Department | Rating | NumRatings |
| :------- | :-------- | :--------- | :----: | :--------: |
| Doe      | John      | CSC        | 3.5    | 24         |

In [4]:
!pip install itables
import pandas as pd
import requests
import itables
import json
from bs4 import BeautifulSoup
import re

Requirement already satisfied: itables in /usr/local/lib/python3.10/dist-packages (2.1.0)
Requirement already satisfied: ipython in /usr/local/lib/python3.10/dist-packages (from itables) (7.34.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from itables) (1.25.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from itables) (2.0.3)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.10/dist-packages (from ipython->itables) (67.7.2)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.10/dist-packages (from ipython->itables) (0.19.1)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython->itables) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython->itables) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.10/dist-packages (from ipython->itables) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython->itables) (3.0.45)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython->itables) (2.16.1)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython->itables) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython->itables) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython->itables) (4.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->itables) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->itables) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->itables) (2024.1)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython->itables) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython->itables) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->itables) (0.2.13)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->itables) (1.16.0)

In [34]:
# df_ratings = pd.read_json('professor_ratings.json')
# itables.show(df_ratings)

with open('professor_ratings.json') as f:
    data = json.load(f)

df_ratings = pd.json_normalize(data['data'])
columns = ["lastName", "firstName", "department", "numEvals", "overallRating", "materialClear", "studentDifficulties", "courses"]
df_ratings = df_ratings[columns]

for index, row in df_ratings[(df_ratings['firstName'].str.split().str.len()) > 1].iterrows():
    name = row['firstName']
    firstname, middlename = name.split()
    df_ratings.loc[index, 'firstName'] = firstname

In [35]:
df_ratings

,lastName,firstName,department,numEvals,overallRating,materialClear,studentDifficulties,courses
0,Mahjoor,Parisa,CHEM,17,0.64,0.82,0.45,"[CHEM 110, CHEM 127, CHEM 316]"
1,Clark,Chris,CSC,12,3.70,3.62,3.70,"[CPE 103, CSC 103, CPE 123, CRP 430, CPE 481, ..."
2,LaGuire,Tiev,FSN,13,2.57,2.57,2.71,"[FSN 210, FSN 250, FSN 251]"
3,Lathrop,Amanda,FSN,8,2.22,2.67,1.89,"[FSN 125, FSN 275]"
4,Rucci,Nancy,SPAN,12,2.50,2.50,2.64,"[SPAN 101, SPAN 102, SPAN 111, SPAN 201, SPAN ..."
...,...,...,...,...,...,...,...,...
1857,Slayter,Erik,BUS,71,3.68,3.69,3.70,"[AGB 214, BUS 214, BUS 215, BUS 221, AGB 260, ..."
1858,Neal,Emily,BIO,36,1.94,2.03,1.79,"[BIO 161, BIO 221, MCRO 221]"
1859,Glavan,Matthew,MATH,10,2.64,2.27,2.27,"[MATH 118, MATH 221]"
1860,Jansen,Rebecca,CE,2,1.26,1.01,0.75,[CE 204]
1861,Griffin,Lanny,BMED,44,2.77,2.57,2.68,"[MATE 210, BIO 213, BMED 213, BRAE 213, ENGR 2..."

Now we want to collect the salary data of each professor so that we can further analyze it.

Cal Poly Professor salaries scraped from https://afd.calpoly.edu/payroll/compensation_report/state/

In [7]:
!pip install icecream
import pandas as pd
import requests
from bs4 import BeautifulSoup
from icecream import ic
import csv

headers = {
    'User-Agent': r"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 " ,
    'Accept-Language': 'en-US,en;q=0.5'
}

url = "https://afd.calpoly.edu/payroll/compensation_report/state/"

response = requests.get(url, headers = headers)
soup = BeautifulSoup(response.content, "html.parser")

doc = soup.find('div', id='large_report')

names = doc.find_all("h3")
tables = doc.find_all("table")

with open("salaries.csv", "w") as file:
    writer = csv.writer(file)
    writer.writerow( ("name", "avgPay"))

    for i in range(len(names)):
        name = names[i].text

        earnings = tables[i].find_all("td")[-3:]
        nonzero = [float(e.text.replace(",", "")) for e in earnings if float(e.text.replace(",", "") ) > 0]

        if len(nonzero) > 0:
            avg = sum(nonzero) / len(nonzero)
        else:
            avg = 0

        #ic(name)
        #ic(avg)
        writer.writerow((name,avg))

Requirement already satisfied: icecream in /usr/local/lib/python3.10/dist-packages (2.1.3)
Requirement already satisfied: colorama>=0.3.9 in /usr/local/lib/python3.10/dist-packages (from icecream) (0.4.6)
Requirement already satisfied: pygments>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from icecream) (2.16.1)
Requirement already satisfied: executing>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from icecream) (2.0.1)
Requirement already satisfied: asttokens>=2.0.1 in /usr/local/lib/python3.10/dist-packages (from icecream) (2.4.1)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from asttokens>=2.0.1->icecream) (1.16.0)

After we scrapped all the necessary informations from the website and store it in a csv, we can now further clean and format the dataframe.

In [8]:
import pandas as pd

df_payroll = pd.read_csv('salaries.csv')

# Extracting first and last name from payroll dataframe to match polyrating name format
for index, row in df_payroll.iterrows():
    name = row['name']
    lastname, firstname_middle = name.split(", ")
    firstname_parts = firstname_middle.split()
    firstname = firstname_parts[0]
    df_payroll.loc[index, 'firstName'] = firstname
    df_payroll.loc[index, 'lastName'] = lastname

df_payroll['avgPay'] = df_payroll['avgPay'].round(2)

In [9]:
# Exctracting out all the periods to ensure data consistency
df_payroll['name'] = df_payroll['name'].str.replace('.', '')
df_payroll

                            name     avgPay firstName     lastName
0               Aagaard, Sofie J   91650.96     Sofie      Aagaard
1                Abba, Michele M   57789.41   Michele         Abba
2        Abelli-Amen, Ella Carol    4778.25      Ella  Abelli-Amen
3               Abeloos, Diego V   67907.67     Diego      Abeloos
4     Abercromby, Kira Jorgensen  123885.33      Kira   Abercromby
...                          ...        ...       ...          ...
4728               Zook, Garet R   63830.44     Garet         Zook
4729           Zumalt, Julia Mae    3311.86     Julia       Zumalt
4730      Zumbro, Emma Catherine    6752.28      Emma       Zumbro
4731       Zuzow, Lynnetta Robin   68914.67  Lynnetta        Zuzow
4732       Zwarg, Noah Alexander    7695.00      Noah        Zwarg

[4733 rows x 4 columns]

After formatting everything correctly, we would want to check if there is any duplicate names in these two dataframes.

In [10]:
duplicates_rating = df_ratings.groupby(['firstName', 'lastName']).filter(lambda x: len(x) > 1)
print("There is " + str(len(duplicates_rating)) + " duplicates first and last names in the rating dataframe")

duplicates_payroll = df_payroll.groupby(['firstName', 'lastName']).filter(lambda x: len(x) > 1)
print("There is " + str(len(duplicates_payroll)) + " duplicates first and last names in the payroll dataframe")

There is 9 duplicates first and last names in the rating dataframe
There is 19 duplicates first and last names in the payroll dataframe

This is the duplicate rating dataframe, where through meticulous investigation, we found out that, Chris Clark is the same professor that teaches two department, Mary Armstrong are two different professor that doesn't teach anymore, Michael Miller are two different professor, where one teaches and one doesn't, and Todd Hagobian that are the same professor that teaches.

In [11]:
duplicates_rating.sort_values(by='firstName', inplace=True)
duplicates_rating

,lastName,firstName,department,numEvals,overallRating,materialClear,studentDifficulties,courses
1,Clark,Chris,CSC,12,3.70,3.62,3.70,"[CPE 103, CSC 103, CPE 123, CRP 430, CPE 481, ..."
345,Clark,Chris,CRP,16,3.75,3.75,3.75,"[CRP 101, CRP 212, CRP 404, CRP 408, CRP 412, ..."
957,Armstrong,Mary,LA,4,3.20,3.20,3.20,"[WS 301, BUS 322]"
1244,Armstrong,Mary,ENGL,21,3.59,3.73,3.64,"[WS 301, WS 310, ENGL 334, WS 340, ENGL 345, W..."
62,Miller,Michael,ART,33,2.79,2.97,2.59,"[ART 101, ART 201, ART 203, ART 301, ART 335, ..."
728,Miller,Michael,MATH,8,3.62,3.75,3.74,"[MATH 141, MATH 142]"
1601,Miller,Michael,MATH,1,4.00,4.00,4.00,[MATH]
1013,Hagobian,Todd,KINE,3,3.40,3.40,3.00,[KINE 303]
1577,Hagobian,Todd,KINE,5,3.17,3.17,3.33,[KINE 303]

Therefore we decided to drop the two Mary Armstrong and the Micheal Miller from ART department, besides from that, we also decided to combine the same professor to ensure data consistency from the original dataframe.

In [12]:
df_ratings.drop(index=62, inplace=True)
df_ratings.drop(index=957, inplace=True)
df_ratings.drop(index=1244, inplace=True)

In [13]:
# Compute product of evaluations and ratings for weighted average calculation
df_ratings['weightedOverallRating'] = df_ratings['numEvals'] * df_ratings['overallRating']
df_ratings['weightedMaterialClear'] = df_ratings['numEvals'] * df_ratings['materialClear']
df_ratings['weightedStudentDifficulties'] = df_ratings['numEvals'] * df_ratings['studentDifficulties']

# Aggregating function
aggregation_functions = {
    'department': 'first',  # Keep the first department
    'numEvals': 'sum',
    'weightedOverallRating': 'sum',
    'weightedMaterialClear': 'sum',
    'weightedStudentDifficulties': 'sum',
    'courses': lambda x: list(set(sum(x, [])))  # Flatten list and remove duplicates
}

# Group by first and last name and aggregate
df_ratings = df_ratings.groupby(['firstName', 'lastName']).agg(aggregation_functions)

# Calculate weighted averages
df_ratings['overallRating'] = df_ratings['weightedOverallRating'] / df_ratings['numEvals']
df_ratings['materialClear'] = df_ratings['weightedMaterialClear'] / df_ratings['numEvals']
df_ratings['studentDifficulties'] = df_ratings['weightedStudentDifficulties'] / df_ratings['numEvals']

# Drop weighted columns as they are no longer needed
df_ratings.drop(columns=['weightedOverallRating', 'weightedMaterialClear', 'weightedStudentDifficulties'], inplace=True)

# Reset index to make firstName and lastName columns again
df_ratings.reset_index(inplace=True)

df_ratings

,firstName,lastName,department,numEvals,courses,overallRating,materialClear,studentDifficulties
0,Lubomir,Stanchev,CSC,2,"[DATA 301, CSC 365]",3.00,2.00,3.50
1,Aaron,Estrada,PSY,34,"[PSY 323, PSY 372, PSY 555, PSY 252, PSY 305, ...",2.58,2.73,2.58
2,Aaron,Keen,CSC,90,"[CSC 349, CSC 530, CPE 431, CPE 102, CSC 101, ...",2.88,2.89,2.77
3,Aaron,Newcomer,MATH,15,"[MATH 142, MATH 143]",3.00,3.15,2.85
4,Aaron,Rodriguez,ES,35,"[SOC 316, ES 112, ES 212, ES 210, ES 323, ES 1...",3.37,3.43,3.17
...,...,...,...,...,...,...,...,...
1851,jnan,blau,COMS,24,"[COMS 416, SPC 208, SPC 101, COMS 208, COMS 31...",3.60,3.66,3.34
1852,robert,schaeffer,SOC,18,"[SOC 110, SOC 395, SOC 218, SOC 118]",3.50,3.17,3.44
1853,sasha,poma,ENGL,2,"[ENGL 133, ENGL 134]",4.00,4.00,4.00
1854,virginia,callow,IME,36,"[IME 418, IME 410, IME 315, IME 320, IME 319, ...",2.12,1.97,2.15
1855,william,gawthrop,PHYS,1,[GEOL 205],1.50,1.50,1.50

As we can see now, there is no longer any duplicates in the rating dataframe.

In [14]:
duplicates_rating = df_ratings.groupby(['firstName', 'lastName']).filter(lambda x: len(x) > 1)
print("There is " + str(len(duplicates_rating)) + " duplicates first and last names in the rating dataframe")

There is 0 duplicates first and last names in the rating dataframe

After clearing out duplicates and ensuring the data consistency within the rating dataframe, we should do the same with the payroll dataframe.

In [15]:
duplicates_payroll.sort_values(by='firstName', inplace=True)
duplicates_payroll

                         name     avgPay firstName  lastName
3652         Russell, Craig H   47821.00     Craig   Russell
3653     Russell, Craig Nolan   67439.39     Craig   Russell
2668        Marshall, David C   64006.75     David  Marshall
2669        Marshall, David D  152803.00     David  Marshall
2670    Marshall, David James  115574.67     David  Marshall
3712  Sanchez, David Cardenas     499.90     David   Sanchez
3711         Sanchez, David A   12752.00     David   Sanchez
2032      Johnson, Eric James   24298.45      Eric   Johnson
2033          Johnson, Eric R   97206.38      Eric   Johnson
100    Anderson, Jeffery Lynn   32264.61   Jeffery  Anderson
101       Anderson, Jeffery M   76299.08   Jeffery  Anderson
3121       Oliver, John Edman    5237.67      John    Oliver
3122           Oliver, John Y  106037.33      John    Oliver
1590         Grimes, Joseph E   56073.17    Joseph    Grimes
1591    Grimes, Joseph Edward   13166.68    Joseph    Grimes
4575     Williams, Kevin Todd   68301.42     Kevin  Williams
4574   Williams, Kevin Thomas   83864.03     Kevin  Williams
2894        Miller, Michael G   53198.59   Michael    Miller
2893        Miller, Michael D   18590.90   Michael    Miller

First we can see if all the people in the duplicates have ratings, therefore we can do a left merge, if the person doesn't have ratings, we can just drop them, since they might not be professor, but just a faculty member.

In [16]:
duplicates_payrollRating = duplicates_payroll.merge(df_ratings, on=['firstName', 'lastName'], how="left")
na_payrollRating = duplicates_payrollRating[duplicates_payrollRating['overallRating'].isna()]
na_payrollRating

,name,avgPay,firstName,lastName,department,numEvals,courses,overallRating,materialClear,studentDifficulties
5,"Sanchez, David Cardenas",499.90,David,Sanchez,NaN,NaN,NaN,NaN,NaN,NaN
6,"Sanchez, David A",12752.00,David,Sanchez,NaN,NaN,NaN,NaN,NaN,NaN
7,"Johnson, Eric James",24298.45,Eric,Johnson,NaN,NaN,NaN,NaN,NaN,NaN
8,"Johnson, Eric R",97206.38,Eric,Johnson,NaN,NaN,NaN,NaN,NaN,NaN
9,"Anderson, Jeffery Lynn",32264.61,Jeffery,Anderson,NaN,NaN,NaN,NaN,NaN,NaN
10,"Anderson, Jeffery M",76299.08,Jeffery,Anderson,NaN,NaN,NaN,NaN,NaN,NaN
13,"Grimes, Joseph E",56073.17,Joseph,Grimes,NaN,NaN,NaN,NaN,NaN,NaN
14,"Grimes, Joseph Edward",13166.68,Joseph,Grimes,NaN,NaN,NaN,NaN,NaN,NaN

After we know that these are not professors, therefore we can just drop them thorugh using their index.

In [17]:
df_payroll.drop(index=3711, inplace=True)
df_payroll.drop(index=3712, inplace=True)
df_payroll.drop(index=2032, inplace=True)
df_payroll.drop(index=2033, inplace=True)
df_payroll.drop(index=100, inplace=True)
df_payroll.drop(index=101, inplace=True)
df_payroll.drop(index=1590, inplace=True)
df_payroll.drop(index=1591, inplace=True)

Now we want to focus on the names that actually have ratings

In [18]:
notna_payrollRating = duplicates_payrollRating[duplicates_payrollRating['overallRating'].notna()]

In [19]:
notna_payrollRating

,name,avgPay,firstName,lastName,department,numEvals,courses,overallRating,materialClear,studentDifficulties
0,"Russell, Craig H",47821.00,Craig,Russell,MU,107.0,"[MU 101, MU 121, MU 321, MU 329, MU 120, MU 22...",3.660000,3.560000,3.580000
1,"Russell, Craig Nolan",67439.39,Craig,Russell,MU,107.0,"[MU 101, MU 121, MU 321, MU 329, MU 120, MU 22...",3.660000,3.560000,3.580000
2,"Marshall, David C",64006.75,David,Marshall,AERO,17.0,"[AERO 301, AERO 304, AERO 405, AERO 306, AERO ...",2.060000,2.560000,1.940000
3,"Marshall, David D",152803.00,David,Marshall,AERO,17.0,"[AERO 301, AERO 304, AERO 405, AERO 306, AERO ...",2.060000,2.560000,1.940000
4,"Marshall, David James",115574.67,David,Marshall,AERO,17.0,"[AERO 301, AERO 304, AERO 405, AERO 306, AERO ...",2.060000,2.560000,1.940000
11,"Oliver, John Edman",5237.67,John,Oliver,CPE,2.0,"[CPE 350, CPE 100]",4.000000,4.000000,4.000000
12,"Oliver, John Y",106037.33,John,Oliver,CPE,2.0,"[CPE 350, CPE 100]",4.000000,4.000000,4.000000
15,"Williams, Kevin Todd",68301.42,Kevin,Williams,IME,35.0,"[IME 141, IME 142]",3.730000,3.180000,3.560000
16,"Williams, Kevin Thomas",83864.03,Kevin,Williams,IME,35.0,"[IME 141, IME 142]",3.730000,3.180000,3.560000
17,"Miller, Michael G",53198.59,Michael,Miller,MATH,9.0,"[MATH, MATH 142, MATH 141]",3.662222,3.777778,3.768889
18,"Miller, Michael D",18590.90,Michael,Miller,MATH,9.0,"[MATH, MATH 142, MATH 141]",3.662222,3.777778,3.768889

Through meticulous investigation by looking at the professor's latest rating from polyratings, I was able to find the professor's full name through the course they used to teach through this website https://schedules.calpoly.edu/index_2224.htm

real professors within this dataframe is Marshall, David D, Russell, Craig H, Oliver, John Y, Williams, Kevin Todd, Miller, Michael G

therefore we can just drop other ones that are not a professor

In [20]:
df_payroll.drop(index=3653, inplace=True)
df_payroll.drop(index=2668, inplace=True)
df_payroll.drop(index=2670, inplace=True)
df_payroll.drop(index=3121, inplace=True)
df_payroll.drop(index=4574, inplace=True)
df_payroll.drop(index=2893, inplace=True)

In [21]:
df_payroll

                            name     avgPay firstName     lastName
0               Aagaard, Sofie J   91650.96     Sofie      Aagaard
1                Abba, Michele M   57789.41   Michele         Abba
2        Abelli-Amen, Ella Carol    4778.25      Ella  Abelli-Amen
3               Abeloos, Diego V   67907.67     Diego      Abeloos
4     Abercromby, Kira Jorgensen  123885.33      Kira   Abercromby
...                          ...        ...       ...          ...
4728               Zook, Garet R   63830.44     Garet         Zook
4729           Zumalt, Julia Mae    3311.86     Julia       Zumalt
4730      Zumbro, Emma Catherine    6752.28      Emma       Zumbro
4731       Zuzow, Lynnetta Robin   68914.67  Lynnetta        Zuzow
4732       Zwarg, Noah Alexander    7695.00      Noah        Zwarg

[4719 rows x 4 columns]

In [22]:
duplicates_payroll = df_payroll.groupby(['firstName', 'lastName']).filter(lambda x: len(x) > 1)
print("There is " + str(len(duplicates_payroll)) + " duplicates first and last names in the payroll dataframe")

There is 0 duplicates first and last names in the payroll dataframe

Through these, we have successfully clear out the dataframe and ensured data consistency.

In [23]:
print("The number of payroll is " + str(len(df_payroll)))
print("The number of rating is " + str(len(df_ratings)))
df_payRating = df_payroll.merge(df_ratings, on=["firstName", "lastName"])

The number of payroll is 4719
The number of rating is 1856

In [24]:
df_payRating

,name,avgPay,firstName,lastName,department,numEvals,courses,overallRating,materialClear,studentDifficulties
0,"Abercromby, Kira Jorgensen",123885.33,Kira,Abercromby,AERO,20,"[AERO 353, AERO 451, AERO 351, AERO 101, AERO ...",3.39,3.34,3.42
1,"Abney, Keith A",99122.78,Keith,Abney,PHIL,138,"[PHIL 201, PHIL 339, PHIL 335, PHIL 327, PHIL ...",2.31,2.61,2.05
2,"Adams, Nikki L",116394.67,Nikki,Adams,BIO,27,"[ZOO 336, BIO 336, BIO 160, MSC 440, BIO 440, ...",2.82,2.68,2.75
3,"Adan, Elizabeth",130039.99,Elizabeth,Adan,ART,37,"[ART 112, ART 315, WGS 210, ART 311, ART 312, ...",3.56,3.66,3.48
4,"Agbo, Samuel O",85824.17,Samuel,Agbo,EE,80,"[EE 112, EE 151, EE 307, EE 228, EE 212, EE 31...",1.23,1.28,1.01
...,...,...,...,...,...,...,...,...,...,...
890,"Zhang, Shanju",117869.34,Shanju,Zhang,CHEM,25,"[CHEM 124, CHEM 351, CHEM 125, CHEM 127, CHEM ...",2.88,2.81,2.77
891,"Zigler, David F",95367.33,David,Zigler,CHEM,13,"[CHEM 126, CHEM 124, CHEM 125, CHEM 121, CHEM ...",1.16,1.23,1.38
892,"Zoerb, Matthew C",98424.00,Matthew,Zoerb,CHEM,1,[CHEM],3.00,3.00,3.00
893,"Zoller, David J",74328.67,David,Zoller,PHIL,13,"[PHIL 230, PHIL 231, PHIL 335, PHIL 331]",3.23,3.08,3.08
894,"Zumbro, Emma Catherine",6752.28,Emma,Zumbro,ENGL,1,[ENGL 134],0.00,3.00,2.00

next step, get the professor list, match it on, give the na lecture/ta

Information scraped off from https://catalog.calpoly.edu/facultyandstaff/#facultystaffemeritustext

In [25]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from icecream import ic
import csv

headers = {
    'User-Agent': r"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 " ,
    'Accept-Language': 'en-US,en;q=0.5'
}

url = "https://catalog.calpoly.edu/facultyandstaff/#facultystaffemeritustext"

def extract_columns(row_tag):
    """
    Extracts and prints columns from a given table row tag.

    :param row_tag: BeautifulSoup tag representing the table row
    :return: List of column texts
    """
    columns = row_tag.find_all('td')
    column_texts = [column.get_text(separator=" ", strip=True) for column in columns]
    return column_texts

response = requests.get(url, headers = headers)
soup = BeautifulSoup(response.content, "html.parser")

tab = soup.find_all("table")[-1]
rows = tab.find_all("tr")[1:]

with open("position.csv", "w") as file:
    writer = csv.writer(file)
    writer.writerow(["name", "year", "dept", "position", "education"])

    for row in rows:

        cols = extract_columns(row)

        temp, position, education = tuple(cols)

        if(temp.count("(") == 1):
            name, temp = tuple(temp.split("("))
            year, dept = tuple(temp.split(")"))
            cRow=[name.strip(), year.strip(), dept.strip(), position.strip(), education.strip()]

            writer.writerow(cRow)
        else:
            print(cols)

['Lee, Daeun (Philip)  (2023) Accounting', 'Assistant Professor', 'B.S. Duke University, 2011; M.S. Baruch College, 2014; Ph.D. Baruch College, 2021']
['Marlow (Buchanan), Colleen A. (2014) Physics', 'Associate Professor', 'B.S., California Polytechnic State University, San Luis Obispo, 1999; Ph.D., University of Oregon, 2005.']
['Miller, Charles (Tad) R. (1987) Accounting', 'Professor Emeritus (FERP)', 'B.A., College of Wooster, 1970; M.B.A., University of Arizona, 1980; Ph.D., 1987. Certified Public Accountant.']
['Shani, Abraham (Rami) B. (1983) Management, HR, and Information Systems', 'Professor Emeritus (FERP)', 'B.A., University of Tel Aviv, 1972; M.A., 1978; Ph.D., Case Western Reserve University, 1981.']
['Singh, Jagjit (Jay)  (2003) Industrial Technology and Packaging', 'Professor', 'B.S., Poona University, Pune, India, 1992; M.S., Michigan State University, 1998; Ph.D., 2002.']
['Yin, Bingqing (Miranda)  (2021) Marketing', 'Assistant Professor', 'Ph.D., University of Kansas 2019, M.S. Business Administration Washburn University 2011, B.S. Wuhan University of Science and Technology 2009']
['Yu, Xiao-Hua (Helen)  (2000) Electrical Engineering', 'Professor', 'B.S., TianJin University, People’s Republic of China, 1988; M.S., Temple University, 1992; Ph.D., University of California, Irvine, 1998.']
['Zhang, Xiaozheng (Jane)  (2003) Electrical Engineering', 'Professor', 'Diplom, University of Erlangen-Nuremberg, Germany, 1997; Ph.D., Georgia Institute of Technology, 2002.']

After we scrapped the position information of current professors, we can then save it into a csv and then clean it up by storing it in dataframes.

In [26]:
df_position = pd.read_csv('position.csv')

In [27]:
df_position['name'] = df_position['name'].str.replace('.','')

In [28]:
for index, row in df_position.iterrows():
    name = row['name']
    lenName = len(name.split(", "))
    if lenName == 2:
      lastname, firstname_middle = name.split(", ")
    elif lenName == 3:
      lastname, firstname_middle, _ = name.split(", ")
      print(name)
    elif lenName == 4:
      lastname, firstname_middle, _, _ = name.split(", ")
      print(name)
    firstname_parts = firstname_middle.split()
    firstname = firstname_parts[0]
    df_position.loc[index, 'firstName'] = firstname
    df_position.loc[index, 'lastName'] = lastname

Castilow, Dan C, II
Fowler, Thomas , IV, FAIA

In [29]:
df_position

,name,year,dept,position,education,firstName,lastName
0,"Abercromby, Kira J",2008,Aerospace Engineering,Professor,"B.S., University of California, Los Angeles, 1...",Kira,Abercromby
1,"Abo Ismail, Mohammed",2019,Animal Science,Assistant Professor,"B.S., Alexandria University Damanhour, 2000; M...",Mohammed,Abo Ismail
2,"Adams, Nikki L",2002,Biological Sciences,Professor,"B.A., University of California, Santa Barbara,...",Nikki,Adams
3,"Adams, Aubrie S",2017,Communication Studies,Associate Professor,"B.A., Sonoma State University, 2005; M.A., Sac...",Aubrie,Adams
4,"Adams, Elizabeth",2023,Construction Management,Assistant Professor,"B.S., Boise State University, 2001; M.S., Univ...",Elizabeth,Adams
...,...,...,...,...,...,...,...
765,"Zhang, Pei",2022,Experience Industry Management,Assistant Professor,"B.S., Wuhan University of Science and Technolo...",Pei,Zhang
766,"Zhang, Alan",2022,Mechanical Engineering,Assistant Professor,"B.S. University of California, Berkeley 2016, ...",Alan,Zhang
767,"Zigler, David F",2016,Chemistry and Biochemistry,Associate Professor,"B.S., Eastern Illinois University; Ph.D., Virg...",David,Zigler
768,"Zoerb, Matthew C",2015,Chemistry and Biochemistry,Associate Professor,"B.S., UT Chattanooga, 2006; Ph.D., Univeristy ...",Matthew,Zoerb
769,"Zoller, David J",2015,Philosophy,Associate Professor,"B.A. Xavier University, 2003; M.A., Fordham Un...",David,Zoller

In [30]:
duplicates_position = df_position.groupby(['firstName', 'lastName']).filter(lambda x: len(x) > 1)
print("There is " + str(len(duplicates_position)) + " duplicates first and last names in the position dataframe")

There is 2 duplicates first and last names in the position dataframe

In [31]:
df_payRating

,name,avgPay,firstName,lastName,department,numEvals,courses,overallRating,materialClear,studentDifficulties
0,"Abercromby, Kira Jorgensen",123885.33,Kira,Abercromby,AERO,20,"[AERO 353, AERO 451, AERO 351, AERO 101, AERO ...",3.39,3.34,3.42
1,"Abney, Keith A",99122.78,Keith,Abney,PHIL,138,"[PHIL 201, PHIL 339, PHIL 335, PHIL 327, PHIL ...",2.31,2.61,2.05
2,"Adams, Nikki L",116394.67,Nikki,Adams,BIO,27,"[ZOO 336, BIO 336, BIO 160, MSC 440, BIO 440, ...",2.82,2.68,2.75
3,"Adan, Elizabeth",130039.99,Elizabeth,Adan,ART,37,"[ART 112, ART 315, WGS 210, ART 311, ART 312, ...",3.56,3.66,3.48
4,"Agbo, Samuel O",85824.17,Samuel,Agbo,EE,80,"[EE 112, EE 151, EE 307, EE 228, EE 212, EE 31...",1.23,1.28,1.01
...,...,...,...,...,...,...,...,...,...,...
890,"Zhang, Shanju",117869.34,Shanju,Zhang,CHEM,25,"[CHEM 124, CHEM 351, CHEM 125, CHEM 127, CHEM ...",2.88,2.81,2.77
891,"Zigler, David F",95367.33,David,Zigler,CHEM,13,"[CHEM 126, CHEM 124, CHEM 125, CHEM 121, CHEM ...",1.16,1.23,1.38
892,"Zoerb, Matthew C",98424.00,Matthew,Zoerb,CHEM,1,[CHEM],3.00,3.00,3.00
893,"Zoller, David J",74328.67,David,Zoller,PHIL,13,"[PHIL 230, PHIL 231, PHIL 335, PHIL 331]",3.23,3.08,3.08
894,"Zumbro, Emma Catherine",6752.28,Emma,Zumbro,ENGL,1,[ENGL 134],0.00,3.00,2.00

In [32]:
df_payPositionRating = df_payRating.merge(df_position, on=['firstName', 'lastName'], how='left')
df_payPositionRating['position'].fillna('Lecturer/TA', inplace=True)

In [33]:
df_payPositionRating

,name_x,avgPay,firstName,lastName,department,numEvals,courses,overallRating,materialClear,studentDifficulties,name_y,year,dept,position,education
0,"Abercromby, Kira Jorgensen",123885.33,Kira,Abercromby,AERO,20,"[AERO 353, AERO 451, AERO 351, AERO 101, AERO ...",3.39,3.34,3.42,"Abercromby, Kira J",2008,Aerospace Engineering,Professor,"B.S., University of California, Los Angeles, 1..."
1,"Abney, Keith A",99122.78,Keith,Abney,PHIL,138,"[PHIL 201, PHIL 339, PHIL 335, PHIL 327, PHIL ...",2.31,2.61,2.05,NaN,NaN,NaN,Lecturer/TA,NaN
2,"Adams, Nikki L",116394.67,Nikki,Adams,BIO,27,"[ZOO 336, BIO 336, BIO 160, MSC 440, BIO 440, ...",2.82,2.68,2.75,"Adams, Nikki L",2002,Biological Sciences,Professor,"B.A., University of California, Santa Barbara,..."
3,"Adan, Elizabeth",130039.99,Elizabeth,Adan,ART,37,"[ART 112, ART 315, WGS 210, ART 311, ART 312, ...",3.56,3.66,3.48,"Adan, Elizabeth",2007,"Women's, Gender and Queer Studies, Interdiscip...",Professor and WGQS Department Chair,"B.A., University of California, Davis, 1993; M..."
4,"Agbo, Samuel O",85824.17,Samuel,Agbo,EE,80,"[EE 112, EE 151, EE 307, EE 228, EE 212, EE 31...",1.23,1.28,1.01,"Agbo, Samuel O",1991,Electrical Engineering,Professor,"B.Sc., University of Nigeria, 1975; M.S.E., Un..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
890,"Zhang, Shanju",117869.34,Shanju,Zhang,CHEM,25,"[CHEM 124, CHEM 351, CHEM 125, CHEM 127, CHEM ...",2.88,2.81,2.77,"Zhang, Shanju",2011,Chemistry and Biochemistry,Professor,"B.S., Jilin University, People's Republic of C..."
891,"Zigler, David F",95367.33,David,Zigler,CHEM,13,"[CHEM 126, CHEM 124, CHEM 125, CHEM 121, CHEM ...",1.16,1.23,1.38,"Zigler, David F",2016,Chemistry and Biochemistry,Associate Professor,"B.S., Eastern Illinois University; Ph.D., Virg..."
892,"Zoerb, Matthew C",98424.00,Matthew,Zoerb,CHEM,1,[CHEM],3.00,3.00,3.00,"Zoerb, Matthew C",2015,Chemistry and Biochemistry,Associate Professor,"B.S., UT Chattanooga, 2006; Ph.D., Univeristy ..."
893,"Zoller, David J",74328.67,David,Zoller,PHIL,13,"[PHIL 230, PHIL 231, PHIL 335, PHIL 331]",3.23,3.08,3.08,"Zoller, David J",2015,Philosophy,Associate Professor,"B.A. Xavier University, 2003; M.A., Fordham Un..."
894,"Zumbro, Emma Catherine",6752.28,Emma,Zumbro,ENGL,1,[ENGL 134],0.00,3.00,2.00,NaN,NaN,NaN,Lecturer/TA,NaN